config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.create(restaurant_params)

    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :rating)
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheapAdvisor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :rating %>:
  <%= f.text_field :rating %><br />

  <%= f.label :address %>:
  <%= f.text_field :address %><br />

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<%= render "form" %>

app/views/restaurants/index.html.erb
<h1>All the Restaurants</h1>

<ul>
  <% @restaurants.each do |resto| %>
    <li><%= link_to resto.name, restaurant_path(resto) %> (<%= resto.rating %>)</li>
  <% end %>
</ul>

<p><%= link_to "Add a restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %></p>

<p><%= @restaurant.rating %> stars</p>

<p><%= link_to "all the restaurants", restaurants_path %></p>

<p><%= link_to "edit this restaurant", edit_restaurant_path(@restaurant) %></p>

<p><%= link_to "delete this restaurant", restaurant_path(@restaurant), method: :delete %></p>